//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearanceSystem.Offices.Employee.Saving_And_Credit
{


    public partial class Ignore_Case
    {
    }
}
